x-airflow-common:
  &airflow-common
  build:
    context: ./airflow
    dockerfile: Dockerfile.airflow
  environment:
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres/airflow
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__WEBSERVER__RBAC: 'true'
    AIRFLOW__WEBSERVER__AUTH_BACKENDS: 'airflow.providers.cncf.kubernetes.auth_backend.kubernetes_auth'
    _JAVA_OPTIONS: "-Xmx768m"
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_HOST: greenplum
    DB_PORT: ${DB_PORT}
    DB_NAME: ${DB_NAME}
    API_KEY: ${API_KEY}
    SYMBOL: ${SYMBOL}
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./raw_data:/data/raw
    - .:/opt/airflow/project
  networks:
    - etl_network

services:
  greenplum:
    image: andruche/greenplum:7
    container_name: greenplum
    hostname: greenplum
    ports:
      - "5432:5432"
    environment:
      GREENPLUM_USER: ${DB_USER}
      GREENPLUM_PASSWORD: ${DB_PASSWORD}
      GREENPLUM_DATABASE: ${DB_NAME}
    volumes:
      - greenplum_data:/data
      - ./greenplum/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etl_network

  airflow_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    networks:
      - etl_network

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash -c "airflow db migrate && airflow users create --username admin --password admin --firstname Airflow --lastname User --role Admin --email admin@example.com"
    profiles: [init]
    depends_on:
      - airflow_postgres

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    profiles: [scheduler]
    depends_on:
      - airflow_postgres
      - greenplum

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    profiles: [webserver]
    depends_on:
      - airflow_postgres
      - greenplum

  airflow-worker:
    <<: *airflow-common
    container_name: airflow-worker
    command: worker
    profiles: [worker]
    depends_on:
      - airflow_postgres
      - greenplum

volumes:
  greenplum_data:
  airflow_postgres_data:

networks:
  etl_network:
    driver: bridge