version: '3.8'

x-airflow-common:
  &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-airflow-custom}:latest
  build:
    context: ./airflow
    dockerfile: Dockerfile.airflow
  user: "${AIRFLOW_UID:-50000}:0"
  environment:
    AIRFLOW_HOME: /opt/airflow
    AIRFLOW_UID: ${AIRFLOW_UID:-50000}
    AIRFLOW_GID: 0
    AIRFLOW_WEBSERVER_PORT: 8080
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow_postgres:5432/airflow
    AIRFLOW__WEBSERVER__SECRET_KEY: super-secret-key-change-me # REMEMBER TO CHANGE THIS IN PRODUCTION!
    AIRFLOW__WEBSERVER__RBAC: 'True'
    AIRFLOW__WEBSERVER__AUTH_BACKENDS: 'airflow.www.security.authentication.basic_auth'
    _JAVA_OPTIONS: "-Xmx768m"
    DB_USER: ${DB_USER}
    DB_PASSWORD: ${DB_PASSWORD}
    DB_HOST: greenplum
    DB_PORT: ${DB_PORT}
    DB_NAME: ${DB_NAME}
    API_KEY: ${API_KEY}
    SYMBOL: ${SYMBOL}
    PYTHONPATH: /opt/airflow/project:/opt/airflow/dags
    AIRFLOW_USER: ${AIRFLOW_USER}
    AIRFLOW_PASSWORD: ${AIRFLOW_PASSWORD}
    # ADD THIS LINE FOR GREENPLUM CONNECTION
    AIRFLOW_CONN_GREENPLUM_CONN: postgresql://gpadmin:12345678@greenplum:5432/postgres
  volumes:
    - ./raw_data:/data/raw:rw,delegated
    - ./airflow/dags:/opt/airflow/dags:rw,delegated
    - ./logs:/opt/airflow/logs:rw,delegated
    - .:/opt/airflow/project:rw,delegated
  networks:
    - etl_custom_network
  mem_limit: 6g

services:
  greenplum:
    image: andruche/greenplum:7
    container_name: greenplum
    hostname: greenplum
    ports:
      - "5432:5432"
    environment:
      GREENPLUM_USER: ${DB_USER}
      GREENPLUM_PASSWORD: ${DB_PASSWORD}
      GREENPLUM_DATABASE: ${DB_NAME}
    volumes:
      - greenplum_data:/data
    networks:
      - etl_custom_network

  airflow_postgres:
    image: postgres:13
    container_name: airflow_postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_postgres_data:/var/lib/postgresql/data
    networks:
      - etl_custom_network

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    profiles: [init]
    command: bash -cx "airflow db migrate && airflow users create --username ${AIRFLOW_USER} --password ${AIRFLOW_PASSWORD} --firstname Airflow --lastname User --role Admin --email admin@example.com || true"
    depends_on:
      - airflow_postgres
    networks:
      - etl_custom_network

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    profiles: [scheduler]
    depends_on:
      - airflow_postgres
      - greenplum
    networks:
      - etl_custom_network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    profiles: [webserver]
    depends_on:
      - airflow_postgres
      - greenplum
    networks:
      - etl_custom_network

volumes:
  greenplum_data:
  airflow_postgres_data:

networks:
  etl_custom_network:
    external: true
    name: finance_etl_network