FROM apache/airflow:2.8.1-python3.9

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libpq-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN mkdir -p /opt/airflow/project
ENV AIRFLOW_HOME=/opt/airflow